name: Test the Build

on:
  # test on PRs and double-test on merges to master, or manually.
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Build tools
      run: |
          python -m pip install --upgrade pip
          pip install build
    - name: Build
      run: |
          python -m build --wheel --sdist
